---
seed: 1024

dataset:
  input_dim: 3
  output_dim: 2
  input_len: 12
  output_len: 3
  dataloader: dataloader_all_sensors_seq2seq

model:
  name: seq2seq
  type: seq2seq

  geo_hiddens: [32,32]
  rnn_type: [MyGRUCell, MyGRUCell]
  rnn_hiddens: [128, 128]
  graph_type: [None, None]
  
training:
  batch_size: 4
  
  wd: 0
  lr: 0.01
  lr_decay_step: 7020
  lr_decay_factor: 0.1
  clip_gradient: 5

  use_sampling: True
  cl_decay_steps: 2000

  early_stop_metric: rmse
  early_stop_epoch: 200
